name: WWW-SherlockSearch
version: 0.18
license: perl
distribution_type: module
requires:
  LWP: 5.60
  HTTP::Cookies: 1.00
  HTTP::Request::Common: 1.00
  HTML::Entities: 0.00
recommends:
  XML::RSS: 0.90
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
